name: Build

on:
  pull_request:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/build.yml"
      - "**/*.rs"

env:
  CARGO_TERM_COLOR: always

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.96.0

      - name: Cache Cargo
        uses: Swatinem/rust-cache@v2

      - name: Build debug
        run: cargo build --workspace

  web:
    name: Web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.96.0
          targets: wasm32-unknown-unknown

      - name: Cache Cargo
        uses: Swatinem/rust-cache@v2

      - name: Build web
        run: cargo build -p dreamstack --target wasm32-unknown-unknown

  windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.96.0

      - name: Cache Cargo
        uses: Swatinem/rust-cache@v2

      - name: Build debug
        run: cargo build --workspace

  macos:
    name: macOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.96.0

      - name: Cache Cargo
        uses: Swatinem/rust-cache@v2

      - name: Build debug
        run: cargo build --workspace
